<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitadaef9852cbeacfcb9a7d14ca7ea2e6b
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'B' =>
        array (
            'Bobet\\Phpmailer\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' =>
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Bobet\\Phpmailer\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitadaef9852cbeacfcb9a7d14ca7ea2e6b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitadaef9852cbeacfcb9a7d14ca7ea2e6b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitadaef9852cbeacfcb9a7d14ca7ea2e6b::$classMap;

        }, null, ClassLoader::class);
    }
}
